import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Random;
import javax.swing.ButtonGroup;
/**
 * The class PlayerChoice implements a dialog box at the start of the game to ask if human should take first turn or computer. It has two
 * radio buttons and one button. It handles the events generated by these components using an event handler. It creates instances of 
 * GameGUI class. The class extends a JDialog.
 *
 * @author (Lala Rukh)
 * @2018.01.07
 */
public class PlayerChoice extends JDialog implements ActionListener {
 Container contentPane = getContentPane();
 JPanel p1 = new JPanel(new GridLayout(1, 0)); 
 JPanel p2 = new JPanel(new FlowLayout());
 JLabel question = new JLabel("Human or computer player first?", SwingConstants.CENTER);
 JRadioButton human = new JRadioButton("Human");
 JRadioButton computer = new JRadioButton("Computer");
 JButton done = new JButton("Done");
 ButtonGroup group = new ButtonGroup();
 private boolean choice;
 JFrame frame = new JFrame();

 /**
  * Constructor for objects of class GameGUI
  */
 public PlayerChoice() {
  setSize(262, 150);
  setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
  //add action listeners and layouts
  p2.add(question);
  p1.add(human);
  human.addActionListener(this);
  human.setSelected(true); //sets human value by default. Can be changed.
  p1.add(computer);
  computer.addActionListener(this);
  p2.add(done);
  p2.add(p1);
  p2.add(done);
  done.addActionListener(this);
  p2.setBackground(Color.WHITE);
  p1.setBackground(Color.WHITE);
  done.setBackground(new Color(169, 9, 9));
  done.setForeground(Color.WHITE);
  //add radio buttons to a group
  group.add(human);
  group.add(computer);
  human.setBackground(Color.WHITE);
  computer.setBackground(Color.WHITE);
  //set colors,fonts and sizes
  question.setFont(new Font("Serif", Font.PLAIN, 18));
  human.setFont(new Font("Serif", Font.PLAIN, 16));
  computer.setFont(new Font("Serif", Font.PLAIN, 16));
  done.setFont(new Font("Serif", Font.PLAIN, 16));
  this.choice = choice;
  contentPane.add("Center", p2);
  setLocationRelativeTo(null);
  setVisible(true);
 }

 /**
  * The method actionPerformed handles the events created by the swing components. It creates instance of GameGUI class based on either 
  * human or computer option selected from the radio buttons on the dialog box.
  */
 public void actionPerformed(ActionEvent event) {
  if (human.isSelected() && event.getSource() == done) { //human is selected and done button is pressed
   choice = true;
   GameGUI gui = new GameGUI(choice); //new instance
   setVisible(false);
  } else if (computer.isSelected() && event.getSource() == done) { //Computer is selected and done button is pressed
   choice = false;
   GameGUI gui = new GameGUI(choice); //new instance
   setVisible(false);
  } else if (event.getSource() == done) { //only done is pressed
   setVisible(false);
   dispose();
  }

 }

}